[general]
import = [
  "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

#[colors.bright]
#black = "#5c6370"
#blue = "#61afef"
#cyan = "#56b6c2"
#green = "#98c379"
#magenta = "#c678dd"
#red = "#e06c75"
#white = "#ffffff"
#yellow = "#d19a66"

#[colors.normal]
#black = "#282c34"
#blue = "#61afef"
#cyan = "#56b6c2"
#green = "#98c379"
#magenta = "#c678dd"
#red = "#e06c75"
#white = "#abb2bf"
#yellow = "#d19a66"

#[colors.primary]
#background = "#282c34"
#foreground = "#abb2bf"

[font]
size = 10

[font.bold]
family = "Hack Nerdfont Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerdfont Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerdfont Mono"
style = "Italic"

[font.normal]
family = "Hack Nerdfont Mono"
style = "Regular"

[window.padding]
x = 8
y = 8

